application:
  port: 4000
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "movie-matrix"
the_movie_db:
  base_url: "https://api.themoviedb.org/3"
