// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.176.1
//   protoc               v5.26.1
// source: movie.proto

/* eslint-disable */
import {
  type CallOptions,
  ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import _m0 from "protobufjs/minimal";

export const protobufPackage = "movie";

export interface Cast {
  id: string;
  name: string;
  role: string;
  profileUrl: string;
}

export interface Movie {
  id: number;
  title: string;
  overview: string;
  voteAverage: number;
  runtime: number;
  releaseDate: string;
  posterUrl?: string | undefined;
  backdropUrl?: string | undefined;
  casting: Cast[];
  genres: string[];
}

export interface MoviePreview {
  id: number;
  title: string;
  posterUrl?: string | undefined;
  voteAverage: number;
}

export interface GetMovieRequest {
  id: number;
}

export interface GetMovieResponse {
  movie: Movie | undefined;
}

export interface SearchMovieRequest {
  query: string;
  limit: number;
}

export interface SearchMovieResponse {
  movies: MoviePreview[];
}

export interface GetMoviesRequest {
  offset: number;
  limit: number;
}

export interface GetMoviesResponse {
  movies: MoviePreview[];
}

function createBaseCast(): Cast {
  return { id: "", name: "", role: "", profileUrl: "" };
}

export const Cast = {
  encode(message: Cast, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.role !== "") {
      writer.uint32(26).string(message.role);
    }
    if (message.profileUrl !== "") {
      writer.uint32(34).string(message.profileUrl);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Cast {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCast();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.role = reader.string();
          continue;
        case 4:
          if (tag !== 34) {
            break;
          }

          message.profileUrl = reader.string();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Cast {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      role: isSet(object.role) ? globalThis.String(object.role) : "",
      profileUrl: isSet(object.profileUrl) ? globalThis.String(object.profileUrl) : "",
    };
  },

  toJSON(message: Cast): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.role !== "") {
      obj.role = message.role;
    }
    if (message.profileUrl !== "") {
      obj.profileUrl = message.profileUrl;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Cast>, I>>(base?: I): Cast {
    return Cast.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Cast>, I>>(object: I): Cast {
    const message = createBaseCast();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.role = object.role ?? "";
    message.profileUrl = object.profileUrl ?? "";
    return message;
  },
};

function createBaseMovie(): Movie {
  return {
    id: 0,
    title: "",
    overview: "",
    voteAverage: 0,
    runtime: 0,
    releaseDate: "",
    posterUrl: undefined,
    backdropUrl: undefined,
    casting: [],
    genres: [],
  };
}

export const Movie = {
  encode(message: Movie, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.overview !== "") {
      writer.uint32(26).string(message.overview);
    }
    if (message.voteAverage !== 0) {
      writer.uint32(37).float(message.voteAverage);
    }
    if (message.runtime !== 0) {
      writer.uint32(40).int32(message.runtime);
    }
    if (message.releaseDate !== "") {
      writer.uint32(50).string(message.releaseDate);
    }
    if (message.posterUrl !== undefined) {
      writer.uint32(58).string(message.posterUrl);
    }
    if (message.backdropUrl !== undefined) {
      writer.uint32(66).string(message.backdropUrl);
    }
    for (const v of message.casting) {
      Cast.encode(v!, writer.uint32(74).fork()).ldelim();
    }
    for (const v of message.genres) {
      writer.uint32(82).string(v!);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): Movie {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMovie();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.overview = reader.string();
          continue;
        case 4:
          if (tag !== 37) {
            break;
          }

          message.voteAverage = reader.float();
          continue;
        case 5:
          if (tag !== 40) {
            break;
          }

          message.runtime = reader.int32();
          continue;
        case 6:
          if (tag !== 50) {
            break;
          }

          message.releaseDate = reader.string();
          continue;
        case 7:
          if (tag !== 58) {
            break;
          }

          message.posterUrl = reader.string();
          continue;
        case 8:
          if (tag !== 66) {
            break;
          }

          message.backdropUrl = reader.string();
          continue;
        case 9:
          if (tag !== 74) {
            break;
          }

          message.casting.push(Cast.decode(reader, reader.uint32()));
          continue;
        case 10:
          if (tag !== 82) {
            break;
          }

          message.genres.push(reader.string());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Movie {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      overview: isSet(object.overview) ? globalThis.String(object.overview) : "",
      voteAverage: isSet(object.voteAverage) ? globalThis.Number(object.voteAverage) : 0,
      runtime: isSet(object.runtime) ? globalThis.Number(object.runtime) : 0,
      releaseDate: isSet(object.releaseDate) ? globalThis.String(object.releaseDate) : "",
      posterUrl: isSet(object.posterUrl) ? globalThis.String(object.posterUrl) : undefined,
      backdropUrl: isSet(object.backdropUrl) ? globalThis.String(object.backdropUrl) : undefined,
      casting: globalThis.Array.isArray(object?.casting) ? object.casting.map((e: any) => Cast.fromJSON(e)) : [],
      genres: globalThis.Array.isArray(object?.genres) ? object.genres.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: Movie): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.overview !== "") {
      obj.overview = message.overview;
    }
    if (message.voteAverage !== 0) {
      obj.voteAverage = message.voteAverage;
    }
    if (message.runtime !== 0) {
      obj.runtime = Math.round(message.runtime);
    }
    if (message.releaseDate !== "") {
      obj.releaseDate = message.releaseDate;
    }
    if (message.posterUrl !== undefined) {
      obj.posterUrl = message.posterUrl;
    }
    if (message.backdropUrl !== undefined) {
      obj.backdropUrl = message.backdropUrl;
    }
    if (message.casting?.length) {
      obj.casting = message.casting.map((e) => Cast.toJSON(e));
    }
    if (message.genres?.length) {
      obj.genres = message.genres;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Movie>, I>>(base?: I): Movie {
    return Movie.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Movie>, I>>(object: I): Movie {
    const message = createBaseMovie();
    message.id = object.id ?? 0;
    message.title = object.title ?? "";
    message.overview = object.overview ?? "";
    message.voteAverage = object.voteAverage ?? 0;
    message.runtime = object.runtime ?? 0;
    message.releaseDate = object.releaseDate ?? "";
    message.posterUrl = object.posterUrl ?? undefined;
    message.backdropUrl = object.backdropUrl ?? undefined;
    message.casting = object.casting?.map((e) => Cast.fromPartial(e)) || [];
    message.genres = object.genres?.map((e) => e) || [];
    return message;
  },
};

function createBaseMoviePreview(): MoviePreview {
  return { id: 0, title: "", posterUrl: undefined, voteAverage: 0 };
}

export const MoviePreview = {
  encode(message: MoviePreview, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    if (message.title !== "") {
      writer.uint32(18).string(message.title);
    }
    if (message.posterUrl !== undefined) {
      writer.uint32(26).string(message.posterUrl);
    }
    if (message.voteAverage !== 0) {
      writer.uint32(37).float(message.voteAverage);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): MoviePreview {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMoviePreview();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        case 2:
          if (tag !== 18) {
            break;
          }

          message.title = reader.string();
          continue;
        case 3:
          if (tag !== 26) {
            break;
          }

          message.posterUrl = reader.string();
          continue;
        case 4:
          if (tag !== 37) {
            break;
          }

          message.voteAverage = reader.float();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MoviePreview {
    return {
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      posterUrl: isSet(object.posterUrl) ? globalThis.String(object.posterUrl) : undefined,
      voteAverage: isSet(object.voteAverage) ? globalThis.Number(object.voteAverage) : 0,
    };
  },

  toJSON(message: MoviePreview): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.posterUrl !== undefined) {
      obj.posterUrl = message.posterUrl;
    }
    if (message.voteAverage !== 0) {
      obj.voteAverage = message.voteAverage;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MoviePreview>, I>>(base?: I): MoviePreview {
    return MoviePreview.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MoviePreview>, I>>(object: I): MoviePreview {
    const message = createBaseMoviePreview();
    message.id = object.id ?? 0;
    message.title = object.title ?? "";
    message.posterUrl = object.posterUrl ?? undefined;
    message.voteAverage = object.voteAverage ?? 0;
    return message;
  },
};

function createBaseGetMovieRequest(): GetMovieRequest {
  return { id: 0 };
}

export const GetMovieRequest = {
  encode(message: GetMovieRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetMovieRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMovieRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMovieRequest {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: GetMovieRequest): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMovieRequest>, I>>(base?: I): GetMovieRequest {
    return GetMovieRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMovieRequest>, I>>(object: I): GetMovieRequest {
    const message = createBaseGetMovieRequest();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseGetMovieResponse(): GetMovieResponse {
  return { movie: undefined };
}

export const GetMovieResponse = {
  encode(message: GetMovieResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.movie !== undefined) {
      Movie.encode(message.movie, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetMovieResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMovieResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.movie = Movie.decode(reader, reader.uint32());
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMovieResponse {
    return { movie: isSet(object.movie) ? Movie.fromJSON(object.movie) : undefined };
  },

  toJSON(message: GetMovieResponse): unknown {
    const obj: any = {};
    if (message.movie !== undefined) {
      obj.movie = Movie.toJSON(message.movie);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMovieResponse>, I>>(base?: I): GetMovieResponse {
    return GetMovieResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMovieResponse>, I>>(object: I): GetMovieResponse {
    const message = createBaseGetMovieResponse();
    message.movie = (object.movie !== undefined && object.movie !== null) ? Movie.fromPartial(object.movie) : undefined;
    return message;
  },
};

function createBaseSearchMovieRequest(): SearchMovieRequest {
  return { query: "", limit: 0 };
}

export const SearchMovieRequest = {
  encode(message: SearchMovieRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.query !== "") {
      writer.uint32(10).string(message.query);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SearchMovieRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchMovieRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.query = reader.string();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchMovieRequest {
    return {
      query: isSet(object.query) ? globalThis.String(object.query) : "",
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: SearchMovieRequest): unknown {
    const obj: any = {};
    if (message.query !== "") {
      obj.query = message.query;
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchMovieRequest>, I>>(base?: I): SearchMovieRequest {
    return SearchMovieRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchMovieRequest>, I>>(object: I): SearchMovieRequest {
    const message = createBaseSearchMovieRequest();
    message.query = object.query ?? "";
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseSearchMovieResponse(): SearchMovieResponse {
  return { movies: [] };
}

export const SearchMovieResponse = {
  encode(message: SearchMovieResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.movies) {
      MoviePreview.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): SearchMovieResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSearchMovieResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.movies.push(MoviePreview.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SearchMovieResponse {
    return {
      movies: globalThis.Array.isArray(object?.movies) ? object.movies.map((e: any) => MoviePreview.fromJSON(e)) : [],
    };
  },

  toJSON(message: SearchMovieResponse): unknown {
    const obj: any = {};
    if (message.movies?.length) {
      obj.movies = message.movies.map((e) => MoviePreview.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SearchMovieResponse>, I>>(base?: I): SearchMovieResponse {
    return SearchMovieResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SearchMovieResponse>, I>>(object: I): SearchMovieResponse {
    const message = createBaseSearchMovieResponse();
    message.movies = object.movies?.map((e) => MoviePreview.fromPartial(e)) || [];
    return message;
  },
};

function createBaseGetMoviesRequest(): GetMoviesRequest {
  return { offset: 0, limit: 0 };
}

export const GetMoviesRequest = {
  encode(message: GetMoviesRequest, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    if (message.offset !== 0) {
      writer.uint32(8).int32(message.offset);
    }
    if (message.limit !== 0) {
      writer.uint32(16).int32(message.limit);
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetMoviesRequest {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMoviesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 8) {
            break;
          }

          message.offset = reader.int32();
          continue;
        case 2:
          if (tag !== 16) {
            break;
          }

          message.limit = reader.int32();
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMoviesRequest {
    return {
      offset: isSet(object.offset) ? globalThis.Number(object.offset) : 0,
      limit: isSet(object.limit) ? globalThis.Number(object.limit) : 0,
    };
  },

  toJSON(message: GetMoviesRequest): unknown {
    const obj: any = {};
    if (message.offset !== 0) {
      obj.offset = Math.round(message.offset);
    }
    if (message.limit !== 0) {
      obj.limit = Math.round(message.limit);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMoviesRequest>, I>>(base?: I): GetMoviesRequest {
    return GetMoviesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMoviesRequest>, I>>(object: I): GetMoviesRequest {
    const message = createBaseGetMoviesRequest();
    message.offset = object.offset ?? 0;
    message.limit = object.limit ?? 0;
    return message;
  },
};

function createBaseGetMoviesResponse(): GetMoviesResponse {
  return { movies: [] };
}

export const GetMoviesResponse = {
  encode(message: GetMoviesResponse, writer: _m0.Writer = _m0.Writer.create()): _m0.Writer {
    for (const v of message.movies) {
      MoviePreview.encode(v!, writer.uint32(10).fork()).ldelim();
    }
    return writer;
  },

  decode(input: _m0.Reader | Uint8Array, length?: number): GetMoviesResponse {
    const reader = input instanceof _m0.Reader ? input : _m0.Reader.create(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetMoviesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1:
          if (tag !== 10) {
            break;
          }

          message.movies.push(MoviePreview.decode(reader, reader.uint32()));
          continue;
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skipType(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetMoviesResponse {
    return {
      movies: globalThis.Array.isArray(object?.movies) ? object.movies.map((e: any) => MoviePreview.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetMoviesResponse): unknown {
    const obj: any = {};
    if (message.movies?.length) {
      obj.movies = message.movies.map((e) => MoviePreview.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetMoviesResponse>, I>>(base?: I): GetMoviesResponse {
    return GetMoviesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetMoviesResponse>, I>>(object: I): GetMoviesResponse {
    const message = createBaseGetMoviesResponse();
    message.movies = object.movies?.map((e) => MoviePreview.fromPartial(e)) || [];
    return message;
  },
};

export type MovieServiceService = typeof MovieServiceService;
export const MovieServiceService = {
  getMovie: {
    path: "/movie.MovieService/GetMovie",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetMovieRequest) => Buffer.from(GetMovieRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetMovieRequest.decode(value),
    responseSerialize: (value: GetMovieResponse) => Buffer.from(GetMovieResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetMovieResponse.decode(value),
  },
  searchMovie: {
    path: "/movie.MovieService/SearchMovie",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: SearchMovieRequest) => Buffer.from(SearchMovieRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => SearchMovieRequest.decode(value),
    responseSerialize: (value: SearchMovieResponse) => Buffer.from(SearchMovieResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => SearchMovieResponse.decode(value),
  },
  getMovies: {
    path: "/movie.MovieService/GetMovies",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetMoviesRequest) => Buffer.from(GetMoviesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer) => GetMoviesRequest.decode(value),
    responseSerialize: (value: GetMoviesResponse) => Buffer.from(GetMoviesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer) => GetMoviesResponse.decode(value),
  },
} as const;

export interface MovieServiceServer extends UntypedServiceImplementation {
  getMovie: handleUnaryCall<GetMovieRequest, GetMovieResponse>;
  searchMovie: handleUnaryCall<SearchMovieRequest, SearchMovieResponse>;
  getMovies: handleUnaryCall<GetMoviesRequest, GetMoviesResponse>;
}

export interface MovieServiceClient extends Client {
  getMovie(
    request: GetMovieRequest,
    callback: (error: ServiceError | null, response: GetMovieResponse) => void,
  ): ClientUnaryCall;
  getMovie(
    request: GetMovieRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetMovieResponse) => void,
  ): ClientUnaryCall;
  getMovie(
    request: GetMovieRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetMovieResponse) => void,
  ): ClientUnaryCall;
  searchMovie(
    request: SearchMovieRequest,
    callback: (error: ServiceError | null, response: SearchMovieResponse) => void,
  ): ClientUnaryCall;
  searchMovie(
    request: SearchMovieRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: SearchMovieResponse) => void,
  ): ClientUnaryCall;
  searchMovie(
    request: SearchMovieRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: SearchMovieResponse) => void,
  ): ClientUnaryCall;
  getMovies(
    request: GetMoviesRequest,
    callback: (error: ServiceError | null, response: GetMoviesResponse) => void,
  ): ClientUnaryCall;
  getMovies(
    request: GetMoviesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetMoviesResponse) => void,
  ): ClientUnaryCall;
  getMovies(
    request: GetMoviesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetMoviesResponse) => void,
  ): ClientUnaryCall;
}

export const MovieServiceClient = makeGenericClientConstructor(
  MovieServiceService,
  "movie.MovieService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): MovieServiceClient;
  service: typeof MovieServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}
